[package]
name = "rust-sqlite"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust-sqlite"
path = "src/main.rs"

[dependencies]
assert_cmd = "2.0.17"
clap = { version = "4.5.45", features = ["derive"] }
predicates = "3.1.3"
tempfile = "3.21.0"
